/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "page-bg": "var(--color-page-bg)",
        "surface-card": "var(--color-surface-card)",
        "surface-subtle": "var(--color-surface-subtle)",
        "surface-elevated": "var(--color-surface-elevated)",
        "primary-navy": "var(--color-primary-navy)",
        "soft-navy": "var(--color-soft-navy)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "copper": "var(--color-copper)",
        "copper-hover": "var(--color-copper-hover)",
        "border-subtle": "var(--color-border-subtle)",
        "input-border": "var(--color-input-border)",
        "input-focus": "var(--color-input-focus)",
        "error-clr": "var(--color-error)",
        "error-container": "var(--color-error-container)",
        "success-container": "var(--color-success-container)",
        "success-text": "var(--color-success-text)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "margin-mobile": "1rem",
        "margin": "2.5rem",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-xl": ["Manrope", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "serif-italic": ["Newsreader", "serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "15px", letterSpacing: "0.03em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-xl": ["38px", { lineHeight: "46px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
